-- MySQL Script generated by MySQL Workbench
-- 03/05/16 23:41:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema frisko
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `frisko` ;

-- -----------------------------------------------------
-- Schema frisko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frisko` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `frisko` ;

-- -----------------------------------------------------
-- Table `frisko`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`roles` ;

CREATE TABLE IF NOT EXISTS `frisko`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`socios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`socios` ;

CREATE TABLE IF NOT EXISTS `frisko`.`socios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_doc` TINYINT NOT NULL DEFAULT 1 COMMENT '1=DNI\n0=RUC',
  `codigo` INT(11) NULL COMMENT 'dni o ruc',
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `telefono` VARCHAR(100) NULL,
  `movil` VARCHAR(100) NULL,
  `email` VARCHAR(150) NULL,
  `address_id` BIGINT NOT NULL COMMENT 'Id de la direccion predeterminada para facturar y envio de mercaderia',
  `cliente` TINYINT NULL DEFAULT 0 COMMENT '0=Cliente\n1=Proveedor\n2=Empleado',
  `proveedor` TINYINT NULL DEFAULT 0,
  `empleado` TINYINT NULL DEFAULT 0,
  `estado` TINYINT NOT NULL DEFAULT 1 COMMENT '1= activo\n0=inactivo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`users` ;

CREATE TABLE IF NOT EXISTS `frisko`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT NOT NULL,
  `role_id` INT NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `agente` TINYINT NOT NULL DEFAULT 0 COMMENT '1=Agente de ventas',
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `role_id_fk_idx` (`role_id` ASC),
  INDEX `socio_id_fk_idx` (`socio_id` ASC),
  CONSTRAINT `role_id_fk_us`
    FOREIGN KEY (`role_id`)
    REFERENCES `frisko`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_us`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`provincias` ;

CREATE TABLE IF NOT EXISTS `frisko`.`provincias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `departamento_id_fk_idx` (`departamento_id` ASC),
  CONSTRAINT `departamento_id_fk_prov`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `frisko`.`departamentos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`distritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`distritos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`distritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `provincia_id` INT NOT NULL,
  `departamento_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `provincia_id_fk_idx` (`provincia_id` ASC),
  INDEX `departamento_id_fk_dist_idx` (`departamento_id` ASC),
  CONSTRAINT `provincia_id_fk_dist`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `frisko`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `departamento_id_fk_dist`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `frisko`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`addresses` ;

CREATE TABLE IF NOT EXISTS `frisko`.`addresses` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `departamento_id` INT NOT NULL,
  `provincia_id` INT NOT NULL,
  `distrito_id` INT NOT NULL,
  `zona` VARCHAR(150) NULL COMMENT 'Urb., AAHH, etc',
  `direccion` VARCHAR(255) NULL,
  `socio_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `socio_id_fk_idx` (`socio_id` ASC),
  INDEX `departamento_id_fk_idx` (`departamento_id` ASC),
  INDEX `provincia_id_idx` (`provincia_id` ASC),
  INDEX `distrito_id_fk_idx` (`distrito_id` ASC),
  CONSTRAINT `socio_id_fk_add`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `departamento_id_fk_add`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `frisko`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `provincia_id_fk_add`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `frisko`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `distrito_id_fk_add`
    FOREIGN KEY (`distrito_id`)
    REFERENCES `frisko`.`distritos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`bancos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`bancos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`bancos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`monedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`monedas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`monedas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `simbolo` VARCHAR(10) NOT NULL,
  `iso` VARCHAR(10) NULL COMMENT 'NUEVO SOL',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`ctacorrientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ctacorrientes` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ctacorrientes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `banco_id` INT NOT NULL,
  `socio_id` BIGINT NULL,
  `moneda_id` INT NOT NULL,
  `tipo` TINYINT NOT NULL DEFAULT 1 COMMENT '0=Ahorros\n1=Cuenta Corriente',
  PRIMARY KEY (`id`),
  INDEX `banco_id_fk_ctaco_idx` (`banco_id` ASC),
  INDEX `socio_id_fk_ctaco_idx` (`socio_id` ASC),
  INDEX `moneda_id_fk_ctaco_idx` (`moneda_id` ASC),
  CONSTRAINT `banco_id_fk_ctaco`
    FOREIGN KEY (`banco_id`)
    REFERENCES `frisko`.`bancos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_ctaco`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `moneda_id_fk_ctaco`
    FOREIGN KEY (`moneda_id`)
    REFERENCES `frisko`.`monedas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`impuestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`impuestos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`impuestos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(150) NULL,
  `tasa` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`documentos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `abreviatura` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`depositos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`depositos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`depositos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`docseries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`docseries` ;

CREATE TABLE IF NOT EXISTS `frisko`.`docseries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `documento_id` INT NOT NULL,
  `deposito_id` INT NOT NULL,
  `serie` INT(3) ZEROFILL NOT NULL,
  `numero` INT(7) ZEROFILL NOT NULL,
  `tipo` INT(2) NULL DEFAULT 0 COMMENT '0=Venta\n1=Caja\n2=Almacen\n3=Manufactura',
  PRIMARY KEY (`id`),
  INDEX `deposito_id_fk_docs_idx` (`deposito_id` ASC),
  INDEX `documento_id_fk_docs_idx` (`documento_id` ASC),
  CONSTRAINT `deposito_id_fk_docs`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `documento_id_fk_docs`
    FOREIGN KEY (`documento_id`)
    REFERENCES `frisko`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`artfamilias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`artfamilias` ;

CREATE TABLE IF NOT EXISTS `frisko`.`artfamilias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`artmarcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`artmarcas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`artmarcas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`umedidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`umedidas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`umedidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `simbolo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`articulos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`articulos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `artfamilia_id` BIGINT NOT NULL,
  `artmarca_id` BIGINT NULL,
  `umedida_id` INT NOT NULL,
  `codigo` VARCHAR(100) NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `imagen` BLOB NULL,
  `tipo` INT(1) NOT NULL DEFAULT 0 COMMENT '0=Articulo\n1=Servicio\n2=Tipo de Gasto\n3=Patrimocio',
  `estado` TINYINT NOT NULL DEFAULT 1 COMMENT '0=Inactivo\n1=Activo',
  PRIMARY KEY (`id`),
  INDEX `artfamilia_id_fk_art_idx` (`artfamilia_id` ASC),
  INDEX `artmarca_id_fk_art_idx` (`artmarca_id` ASC),
  INDEX `umedida_id_idx` (`umedida_id` ASC),
  CONSTRAINT `artfamilia_id_fk_art`
    FOREIGN KEY (`artfamilia_id`)
    REFERENCES `frisko`.`artfamilias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `artmarca_id_fk_art`
    FOREIGN KEY (`artmarca_id`)
    REFERENCES `frisko`.`artmarcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `umedida_id_fk_art`
    FOREIGN KEY (`umedida_id`)
    REFERENCES `frisko`.`umedidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`orden_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_compras` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_compras` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `compra_id` BIGINT NULL,
  `socio_id` BIGINT NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Guardado\n1=Procesado\n2=Anulado',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_oc_idx` (`socio_id` ASC),
  INDEX `compra_id_idx` (`compra_id` ASC),
  CONSTRAINT `socio_id_fk_oc`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compra_id`
    FOREIGN KEY (`compra_id`)
    REFERENCES `frisko`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`compras` ;

CREATE TABLE IF NOT EXISTS `frisko`.`compras` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT NOT NULL,
  `orden_compra_id` BIGINT NULL,
  `ingreso_id` BIGINT NULL,
  `serie` VARCHAR(10) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Grabado\n1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_com_idx` (`socio_id` ASC),
  INDEX `orden_compra_id_fk_com_idx` (`orden_compra_id` ASC),
  INDEX `ingreso_id_fk_com_idx` (`ingreso_id` ASC),
  CONSTRAINT `socio_id_fk_com`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orden_compra_id_fk_com`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `frisko`.`orden_compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingreso_id_fk_com`
    FOREIGN KEY (`ingreso_id`)
    REFERENCES `frisko`.`ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`ingresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ingresos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ingresos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `deposito_id` INT NOT NULL,
  `socio_id` BIGINT NOT NULL,
  `compra_id` BIGINT NULL,
  `orden_compra_id` BIGINT NULL,
  `fecha` DATE NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Grabado\n1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_ing_idx` (`socio_id` ASC),
  INDEX `compra_id_fk_ing_idx` (`compra_id` ASC),
  INDEX `orden_compra_id_fk_ing_idx` (`orden_compra_id` ASC),
  INDEX `deposito_id_fk_ing_idx` (`deposito_id` ASC),
  CONSTRAINT `socio_id_fk_ing`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compra_id_fk_ing`
    FOREIGN KEY (`compra_id`)
    REFERENCES `frisko`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orden_compra_id_fk_ing`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `frisko`.`orden_compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ing`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`ingresos_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ingresos_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ingresos_detalle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ingreso_id` BIGINT NOT NULL,
  `articulo_id` BIGINT NOT NULL,
  `deposito_id` INT NOT NULL DEFAULT 0,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Grabado\n1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `ingreso_id_fk_idet_idx` (`ingreso_id` ASC),
  INDEX `articulo_id_fk_idet_idx` (`articulo_id` ASC),
  CONSTRAINT `ingreso_id_fk_idet`
    FOREIGN KEY (`ingreso_id`)
    REFERENCES `frisko`.`ingresos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_id_fk_idet`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`compras_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`compras_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`compras_detalle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `compra_id` BIGINT NOT NULL,
  `articulo_id` BIGINT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id_fk_comdet_idx` (`compra_id` ASC),
  INDEX `articulo_id_fk_comdet_idx` (`articulo_id` ASC),
  CONSTRAINT `compra_id_fk_comdet`
    FOREIGN KEY (`compra_id`)
    REFERENCES `frisko`.`compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_id_fk_comdet`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`orden_compras_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_compras_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_compras_detalle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `orden_compra_id` BIGINT NOT NULL,
  `articulo_id` BIGINT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `orden_compra_id_fk_ocd_idx` (`orden_compra_id` ASC),
  INDEX `articulo_id_fk_ocd_idx` (`articulo_id` ASC),
  CONSTRAINT `orden_compra_id_fk_ocd`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `frisko`.`orden_compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_id_fk_ocd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`lista_precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`lista_precios` ;

CREATE TABLE IF NOT EXISTS `frisko`.`lista_precios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `moneda_id` INT NOT NULL,
  `tipo_lista` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Compra\n1=Venta',
  `incluir_impuesto` TINYINT NOT NULL DEFAULT 0 COMMENT '0=No Incluir\n1=Si Incluir',
  `estado` TINYINT NOT NULL DEFAULT 1 COMMENT '0=Inactivo\n1=Activo',
  PRIMARY KEY (`id`),
  INDEX `moneda_id_fk_lp_idx` (`moneda_id` ASC),
  INDEX `socios_id_fk_lp_idx` (`socio_id` ASC),
  CONSTRAINT `moneda_id_fk_lp`
    FOREIGN KEY (`moneda_id`)
    REFERENCES `frisko`.`monedas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socios_id_fk_lp`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`articulo_precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`articulo_precios` ;

CREATE TABLE IF NOT EXISTS `frisko`.`articulo_precios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `deposito_id` INT NOT NULL,
  `lista_precio_id` BIGINT NOT NULL,
  `articulo_id` BIGINT NOT NULL,
  `impuesto_id` INT NOT NULL,
  `precio_minimo` DECIMAL(10,2) NULL,
  `precio_estandar` DECIMAL(10,2) NULL,
  `precio_maximo` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `lista_precio_id_fk_ap_idx` (`lista_precio_id` ASC),
  INDEX `impuesto_id_fk_ap_idx` (`impuesto_id` ASC),
  INDEX `articulo_id_fk_ap_idx` (`articulo_id` ASC),
  INDEX `deposito_id_fk_ap_idx` (`deposito_id` ASC),
  CONSTRAINT `lista_precio_id_fk_ap`
    FOREIGN KEY (`lista_precio_id`)
    REFERENCES `frisko`.`lista_precios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `impuesto_id_fk_ap`
    FOREIGN KEY (`impuesto_id`)
    REFERENCES `frisko`.`impuestos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_id_fk_ap`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ap`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`forma_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`forma_pagos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`forma_pagos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 0 COMMENT 'cantidad de dias',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`orden_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_ventas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_ventas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `deposito_id` INT NOT NULL,
  `socio_id` BIGINT NOT NULL,
  `forma_pago_id` BIGINT NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` TINYINT NOT NULL COMMENT '0=Proforma\n1=Orden de Venta\n2=Atendido',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_ov_idx` (`socio_id` ASC),
  INDEX `deposito_id_fk_ov_idx` (`deposito_id` ASC),
  INDEX `user_id_fk_ov_idx` (`user_id` ASC),
  INDEX `forma_pago_id_fk_ov_idx` (`forma_pago_id` ASC),
  CONSTRAINT `socio_id_fk_ov`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ov`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk_ov`
    FOREIGN KEY (`user_id`)
    REFERENCES `frisko`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `forma_pago_id_fk_ov`
    FOREIGN KEY (`forma_pago_id`)
    REFERENCES `frisko`.`forma_pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`orden_ventas_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_ventas_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_ventas_detalle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `orden_venta_id` BIGINT NOT NULL,
  `articulo_id` BIGINT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `orden_venta_id_fk_ovd_idx` (`orden_venta_id` ASC),
  INDEX `articulo_id_fk_ovd_idx` (`articulo_id` ASC),
  CONSTRAINT `orden_venta_id_fk_ovd`
    FOREIGN KEY (`orden_venta_id`)
    REFERENCES `frisko`.`orden_ventas` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_id_fk_ovd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ventas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ventas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `socio_id` BIGINT NOT NULL,
  `documento_id` INT NOT NULL,
  `deposito_id` INT NOT NULL,
  `forma_pago_id` BIGINT NOT NULL,
  `fecha` DATE NOT NULL,
  `serie` INT(3) ZEROFILL NOT NULL,
  `numero` INT(7) ZEROFILL NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Grabado\n1=Procesado',
  `docserie_id` BIGINT NOT NULL,
  `codigo_unico` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_v_idx` (`socio_id` ASC),
  INDEX `documento_id_fk_v_idx` (`documento_id` ASC),
  INDEX `deposito_id_fk_v_idx` (`deposito_id` ASC),
  INDEX `user_id_fk_v_idx` (`user_id` ASC),
  INDEX `forma_pago_id_fk_v_idx` (`forma_pago_id` ASC),
  UNIQUE INDEX `codigo_unico_UNIQUE` (`codigo_unico` ASC),
  CONSTRAINT `socio_id_fk_v`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `documento_id_fk_v`
    FOREIGN KEY (`documento_id`)
    REFERENCES `frisko`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_v`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk_v`
    FOREIGN KEY (`user_id`)
    REFERENCES `frisko`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `forma_pago_id_fk_v`
    FOREIGN KEY (`forma_pago_id`)
    REFERENCES `frisko`.`forma_pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`ventas_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ventas_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ventas_detalle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `venta_id` BIGINT NULL,
  `articulo_id` BIGINT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `serie` LONGTEXT NULL COMMENT 'serie de articulos',
  PRIMARY KEY (`id`),
  INDEX `venta_id_fk_vd_idx` (`venta_id` ASC),
  INDEX `articulo_id_fk_vd_idx` (`articulo_id` ASC),
  CONSTRAINT `venta_id_fk_vd`
    FOREIGN KEY (`venta_id`)
    REFERENCES `frisko`.`ventas` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_id_fk_vd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`guias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`guias` ;

CREATE TABLE IF NOT EXISTS `frisko`.`guias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `deposito_id` INT NOT NULL,
  `orden_venta_id` BIGINT NULL,
  `venta_id` BIGINT NULL,
  `socio_id` BIGINT NOT NULL,
  `documento_id` INT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `fecha` DATE NOT NULL,
  `serie` INT(3) ZEROFILL NOT NULL,
  `numero` INT(7) ZEROFILL NOT NULL,
  `docserie_id` BIGINT NOT NULL,
  `codigo_unico` VARCHAR(100) NULL,
  `estado` TINYINT NOT NULL DEFAULT 0 COMMENT '0=Grabado\n1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_gr_idx` (`socio_id` ASC),
  INDEX `venta_id_fk_gr_idx` (`venta_id` ASC),
  INDEX `orden_venta_id_fk_gr_idx` (`orden_venta_id` ASC),
  INDEX `documento_id_fk_gr_idx` (`documento_id` ASC),
  INDEX `deposito_id_fk_gr_idx` (`deposito_id` ASC),
  UNIQUE INDEX `codigo_unico_UNIQUE` (`codigo_unico` ASC),
  CONSTRAINT `deposito_id_fk_gr`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_gr`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venta_id_fk_gr`
    FOREIGN KEY (`venta_id`)
    REFERENCES `frisko`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orden_venta_id_fk_gr`
    FOREIGN KEY (`orden_venta_id`)
    REFERENCES `frisko`.`orden_ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `documento_id_fk_gr`
    FOREIGN KEY (`documento_id`)
    REFERENCES `frisko`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`guias_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`guias_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`guias_detalle` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `guia_id` BIGINT NOT NULL,
  `articulo_id` BIGINT NOT NULL,
  `deposito_id` INT NOT NULL DEFAULT 0,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `descripcion` VARCHAR(255) NULL,
  `estado` INT NOT NULL DEFAULT 0 COMMENT '0=Grabado\n1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `guia_id_fk_gd_idx` (`guia_id` ASC),
  INDEX `articulo_id_fk_gd_idx` (`articulo_id` ASC),
  CONSTRAINT `guia_id_fk_gd`
    FOREIGN KEY (`guia_id`)
    REFERENCES `frisko`.`guias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_id_fk_gd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frisko`.`articulos_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`articulos_info` ;

CREATE TABLE IF NOT EXISTS `frisko`.`articulos_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `articulo_id` BIGINT NOT NULL,
  `deposito_id` INT NOT NULL,
  `lista_precio_id` BIGINT NOT NULL,
  `articulo_precio_id` BIGINT NULL,
  `existencia` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `reservada` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `disponible` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `articulo_id_fk_info_idx` (`articulo_id` ASC),
  INDEX `deposito_id_fk_info_idx` (`deposito_id` ASC),
  INDEX `lista_precio_id_idx` (`lista_precio_id` ASC),
  INDEX `articulo_precio_id_fk_ainfo_idx` (`articulo_precio_id` ASC),
  CONSTRAINT `articulo_id_fk_ainfo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ainfo`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lista_precio_id_fk_ainfo`
    FOREIGN KEY (`lista_precio_id`)
    REFERENCES `frisko`.`lista_precios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_precio_id_fk_ainfo`
    FOREIGN KEY (`articulo_precio_id`)
    REFERENCES `frisko`.`articulo_precios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `frisko` ;

-- -----------------------------------------------------
-- Placeholder table for view `frisko`.`docseriev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frisko`.`docseriev` (`id` INT, `deposito_id` INT, `documento_id` INT, `nombre` INT, `serie` INT, `numero` INT, `tipo` INT);

-- -----------------------------------------------------
-- View `frisko`.`docseriev`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `frisko`.`docseriev` ;
DROP TABLE IF EXISTS `frisko`.`docseriev`;
USE `frisko`;
CREATE  OR REPLACE VIEW `docseriev` AS
select ds.id, ds.deposito_id, ds.documento_id, d.nombre, ds.serie, ds.numero, ds.tipo
from docseries as ds, documentos as d
where d.id=ds.documento_id
;
USE `frisko`;

DELIMITER $$

USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`distritos_BEFORE_INSERT` $$
USE `frisko`$$
CREATE DEFINER = CURRENT_USER TRIGGER `frisko`.`distritos_BEFORE_INSERT` BEFORE INSERT ON `distritos` FOR EACH ROW
BEGIN
 
END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
