-- MySQL Script generated by MySQL Workbench
-- 03/19/16 11:58:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema frisko
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `frisko` ;

-- -----------------------------------------------------
-- Schema frisko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frisko` DEFAULT CHARACTER SET latin1 ;
USE `frisko` ;

-- -----------------------------------------------------
-- Table `frisko`.`acl_phinxlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`acl_phinxlog` ;

CREATE TABLE IF NOT EXISTS `frisko`.`acl_phinxlog` (
  `version` BIGINT(20) NOT NULL,
  `start_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `end_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`acos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`acos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`acos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `foreign_key` INT(11) NULL DEFAULT NULL,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `lft` INT(11) NULL DEFAULT NULL,
  `rght` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `lft` (`lft` ASC, `rght` ASC),
  INDEX `alias` (`alias` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 276
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`socios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`socios` ;

CREATE TABLE IF NOT EXISTS `frisko`.`socios` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tipo_doc` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1=DNI\n 0=RUC',
  `codigo` INT(11) NULL DEFAULT NULL COMMENT 'dni o ruc',
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(100) NULL DEFAULT NULL,
  `movil` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `address_id` BIGINT(20) NOT NULL COMMENT 'Id de la direccion predeterminada para facturar y envio de mercaderia',
  `cliente` TINYINT(4) NULL DEFAULT '0' COMMENT '0=Cliente1=Proveedor2=Empleado',
  `proveedor` TINYINT(4) NULL DEFAULT '0',
  `empleado` TINYINT(4) NULL DEFAULT '0',
  `estado` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1= activo\n0=inactivo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`addresses` ;

CREATE TABLE IF NOT EXISTS `frisko`.`addresses` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `departamento_id` INT(11) NOT NULL,
  `provincia_id` INT(11) NOT NULL,
  `distrito_id` INT(11) NOT NULL,
  `zona` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Urb., AAHH, etc',
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `socio_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `socio_id_fk_idx` (`socio_id` ASC),
  CONSTRAINT `socio_id_fk_add`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`aros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`aros` ;

CREATE TABLE IF NOT EXISTS `frisko`.`aros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `model` VARCHAR(255) NULL DEFAULT NULL,
  `foreign_key` INT(11) NULL DEFAULT NULL,
  `alias` VARCHAR(255) NULL DEFAULT NULL,
  `lft` INT(11) NULL DEFAULT NULL,
  `rght` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `lft` (`lft` ASC, `rght` ASC),
  INDEX `alias` (`alias` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`aros_acos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`aros_acos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`aros_acos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `aro_id` INT(11) NOT NULL,
  `aco_id` INT(11) NOT NULL,
  `_create` VARCHAR(2) NOT NULL DEFAULT '0',
  `_read` VARCHAR(2) NOT NULL DEFAULT '0',
  `_update` VARCHAR(2) NOT NULL DEFAULT '0',
  `_delete` VARCHAR(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `aro_id` (`aro_id` ASC, `aco_id` ASC),
  INDEX `aco_id` (`aco_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`artfamilias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`artfamilias` ;

CREATE TABLE IF NOT EXISTS `frisko`.`artfamilias` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`artmarcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`artmarcas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`artmarcas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`umedidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`umedidas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`umedidas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `simbolo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`articulos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`articulos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `artfamilia_id` BIGINT(20) NOT NULL,
  `artmarca_id` BIGINT(20) NULL DEFAULT NULL,
  `umedida_id` INT(11) NOT NULL,
  `codigo` VARCHAR(100) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `imagen_dir` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` INT(1) NOT NULL DEFAULT '0' COMMENT '0=Articulo\n1=Servicio\n2=Tipo de Gasto\n3=Patrimocio',
  `estado` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '0=Inactivo\n1=Activo',
  `pdv` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `artfamilia_id_fk_art_idx` (`artfamilia_id` ASC),
  INDEX `artmarca_id_fk_art_idx` (`artmarca_id` ASC),
  INDEX `umedida_id_idx` (`umedida_id` ASC),
  CONSTRAINT `artfamilia_id_fk_art`
    FOREIGN KEY (`artfamilia_id`)
    REFERENCES `frisko`.`artfamilias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `artmarca_id_fk_art`
    FOREIGN KEY (`artmarca_id`)
    REFERENCES `frisko`.`artmarcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `umedida_id_fk_art`
    FOREIGN KEY (`umedida_id`)
    REFERENCES `frisko`.`umedidas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`depositos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`depositos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`depositos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`impuestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`impuestos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`impuestos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `tasa` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`monedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`monedas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`monedas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `simbolo` VARCHAR(10) NOT NULL,
  `iso` VARCHAR(10) NULL DEFAULT NULL COMMENT 'NUEVO SOL',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`lista_precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`lista_precios` ;

CREATE TABLE IF NOT EXISTS `frisko`.`lista_precios` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT(20) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `moneda_id` INT(11) NOT NULL,
  `tipo_lista` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=Compra\n1=Venta',
  `incluir_impuesto` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=No Incluir\n1=Si Incluir',
  `estado` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '0=Inactivo\n1=Activo',
  PRIMARY KEY (`id`),
  INDEX `moneda_id_fk_lp_idx` (`moneda_id` ASC),
  INDEX `socios_id_fk_lp_idx` (`socio_id` ASC),
  CONSTRAINT `moneda_id_fk_lp`
    FOREIGN KEY (`moneda_id`)
    REFERENCES `frisko`.`monedas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socios_id_fk_lp`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`articulo_precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`articulo_precios` ;

CREATE TABLE IF NOT EXISTS `frisko`.`articulo_precios` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deposito_id` INT(11) NOT NULL,
  `lista_precio_id` BIGINT(20) NOT NULL,
  `articulo_id` BIGINT(20) NOT NULL,
  `impuesto_id` INT(11) NOT NULL,
  `precio_minimo` DECIMAL(10,2) NULL DEFAULT NULL,
  `precio_estandar` DECIMAL(10,2) NULL DEFAULT NULL,
  `precio_maximo` DECIMAL(10,2) NULL DEFAULT NULL,
  `incluir_impuesto` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0=Impuesto no incluido, 1= Impuesto Incluido',
  PRIMARY KEY (`id`),
  INDEX `lista_precio_id_fk_ap_idx` (`lista_precio_id` ASC),
  INDEX `impuesto_id_fk_ap_idx` (`impuesto_id` ASC),
  INDEX `articulo_id_fk_ap_idx` (`articulo_id` ASC),
  INDEX `deposito_id_fk_ap_idx` (`deposito_id` ASC),
  CONSTRAINT `articulo_id_fk_ap`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ap`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `impuesto_id_fk_ap`
    FOREIGN KEY (`impuesto_id`)
    REFERENCES `frisko`.`impuestos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lista_precio_id_fk_ap`
    FOREIGN KEY (`lista_precio_id`)
    REFERENCES `frisko`.`lista_precios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frisko`.`articulos_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`articulos_info` ;

CREATE TABLE IF NOT EXISTS `frisko`.`articulos_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `articulo_id` BIGINT(20) NOT NULL,
  `deposito_id` INT(11) NOT NULL,
  `lista_precio_id` BIGINT(20) NOT NULL,
  `articulo_precio_id` BIGINT(20) NULL DEFAULT NULL,
  `existencia` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `reservada` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `disponible` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `articulo_id_fk_info_idx` (`articulo_id` ASC),
  INDEX `deposito_id_fk_info_idx` (`deposito_id` ASC),
  INDEX `lista_precio_id_idx` (`lista_precio_id` ASC),
  INDEX `articulo_precio_id_fk_ainfo_idx` (`articulo_precio_id` ASC),
  CONSTRAINT `articulo_id_fk_ainfo`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_precio_id_fk_ainfo`
    FOREIGN KEY (`articulo_precio_id`)
    REFERENCES `frisko`.`articulo_precios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ainfo`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lista_precio_id_fk_ainfo`
    FOREIGN KEY (`lista_precio_id`)
    REFERENCES `frisko`.`lista_precios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frisko`.`bancos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`bancos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`bancos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`libro_cajas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`libro_cajas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`libro_cajas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `moneda_id` INT(11) NOT NULL,
  `estado` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1=Activo\n2=Procesado',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frisko`.`cajas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`cajas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`cajas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `libro_caja_id` BIGINT(20) NOT NULL,
  `deposito_id` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `fecha_cierre` DATE NULL DEFAULT NULL,
  `estado` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1=Activo\n2=Procesado',
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `libro_caja_id_fk_caja_idx` (`libro_caja_id` ASC),
  INDEX `deposito_id_idx` (`deposito_id` ASC),
  CONSTRAINT `deposito_id_fk_caja`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `libro_caja_id_fk_caja`
    FOREIGN KEY (`libro_caja_id`)
    REFERENCES `frisko`.`libro_cajas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frisko`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`cargos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`cargos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT(20) NULL DEFAULT NULL,
  `impuesto_id` INT(11) NULL DEFAULT NULL,
  `incluir_impuesto` TINYINT(4) NULL DEFAULT '0' COMMENT '0=No incluye impuesto\n1=Incluye Impuesto',
  `nombre` VARCHAR(255) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `estado` TINYINT(4) NOT NULL DEFAULT '1',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  `tipo_cargo` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=Cargo Fijo\n1=Cargo Variable',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_cargo_idx` (`socio_id` ASC),
  CONSTRAINT `socio_id_fk_cargo`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frisko`.`ingresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ingresos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ingresos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deposito_id` INT(11) NOT NULL,
  `socio_id` BIGINT(20) NOT NULL,
  `orden_compra_id` BIGINT(20) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `estado` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0=Grabado 1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_ing_idx` (`socio_id` ASC),
  INDEX `orden_compra_id_fk_ing_idx` (`orden_compra_id` ASC),
  INDEX `deposito_id_fk_ing_idx` (`deposito_id` ASC),
  CONSTRAINT `deposito_id_fk_ing`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_ing`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`compras` ;

CREATE TABLE IF NOT EXISTS `frisko`.`compras` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT(20) NOT NULL,
  `orden_compra_id` BIGINT(20) NULL DEFAULT NULL,
  `ingreso_id` BIGINT(20) NULL DEFAULT NULL,
  `serie` VARCHAR(10) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `fecha` DATE NOT NULL DEFAULT '0000-00-00',
  `estado` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=Grabado\n1=Procesado',
  `total` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `impuesto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `grantotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `pagado` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `saldo` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_com_idx` (`socio_id` ASC),
  INDEX `orden_compra_id_fk_com_idx` (`orden_compra_id` ASC),
  INDEX `ingreso_id_fk_com_idx` (`ingreso_id` ASC),
  CONSTRAINT `ingreso_id_fk_com`
    FOREIGN KEY (`ingreso_id`)
    REFERENCES `frisko`.`ingresos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_com`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`ctacorrientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ctacorrientes` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ctacorrientes` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `banco_id` INT(11) NOT NULL,
  `deposito_id` INT(11) NULL DEFAULT NULL,
  `socio_id` BIGINT(20) NULL DEFAULT NULL,
  `moneda_id` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `nro_cuenta` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '0=Ahorros\n1=Cuenta Corriente',
  `estado` TINYINT(4) NULL DEFAULT '1',
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `banco_id_fk_ctaco_idx` (`banco_id` ASC),
  INDEX `socio_id_fk_ctaco_idx` (`socio_id` ASC),
  INDEX `moneda_id_fk_ctaco_idx` (`moneda_id` ASC),
  INDEX `deposito_id_fk_ctaco_idx` (`deposito_id` ASC),
  CONSTRAINT `banco_id_fk_ctaco`
    FOREIGN KEY (`banco_id`)
    REFERENCES `frisko`.`bancos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ctaco`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `moneda_id_fk_ctaco`
    FOREIGN KEY (`moneda_id`)
    REFERENCES `frisko`.`monedas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_ctaco`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`documentos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`documentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `abreviatura` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`forma_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`forma_pagos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`forma_pagos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `cantidad` INT(11) NOT NULL DEFAULT '0' COMMENT 'cantidad de dias',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`roles` ;

CREATE TABLE IF NOT EXISTS `frisko`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`users` ;

CREATE TABLE IF NOT EXISTS `frisko`.`users` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT(20) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `agente` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '1=Agente de ventas',
  `visibility_roles` LONGTEXT NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `role_id_fk_idx` (`role_id` ASC),
  INDEX `socio_id_fk_idx` (`socio_id` ASC),
  CONSTRAINT `role_id_fk_us`
    FOREIGN KEY (`role_id`)
    REFERENCES `frisko`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_us`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ventas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ventas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `socio_id` BIGINT(20) NOT NULL,
  `orden_venta_id` BIGINT(20) NULL DEFAULT NULL,
  `documento_id` INT(11) NOT NULL,
  `deposito_id` INT(11) NOT NULL,
  `forma_pago_id` BIGINT(20) NOT NULL,
  `fecha` DATE NOT NULL DEFAULT '0000-00-00',
  `serie` INT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT '000',
  `numero` INT(7) UNSIGNED ZEROFILL NOT NULL DEFAULT '0000000',
  `estado` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=Grabado\n1=Procesado',
  `docserie_id` BIGINT(20) NOT NULL DEFAULT '0',
  `codigo_unico` VARCHAR(100) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `impuesto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `grantotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `cobrado` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `saldo` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_unico_UNIQUE` (`codigo_unico` ASC),
  INDEX `socio_id_fk_v_idx` (`socio_id` ASC),
  INDEX `documento_id_fk_v_idx` (`documento_id` ASC),
  INDEX `deposito_id_fk_v_idx` (`deposito_id` ASC),
  INDEX `user_id_fk_v_idx` (`user_id` ASC),
  INDEX `forma_pago_id_fk_v_idx` (`forma_pago_id` ASC),
  CONSTRAINT `deposito_id_fk_v`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `documento_id_fk_v`
    FOREIGN KEY (`documento_id`)
    REFERENCES `frisko`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `forma_pago_id_fk_v`
    FOREIGN KEY (`forma_pago_id`)
    REFERENCES `frisko`.`forma_pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_v`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk_v`
    FOREIGN KEY (`user_id`)
    REFERENCES `frisko`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`cajas_movimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`cajas_movimientos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`cajas_movimientos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `caja_id` BIGINT(20) NULL DEFAULT NULL,
  `ctacorriente_id` BIGINT(20) NULL DEFAULT NULL,
  `compra_id` BIGINT(20) NULL DEFAULT NULL,
  `venta_id` BIGINT(20) NULL DEFAULT NULL,
  `cargo_id` BIGINT(20) NULL DEFAULT NULL,
  `moneda_id` INT(11) NOT NULL DEFAULT '0',
  `concepto` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_cambio` DECIMAL(10,2) NOT NULL DEFAULT '1.00',
  `entrada` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `salida` DECIMAL(10,2) NULL DEFAULT NULL,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `tipo_movimiento` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=Entrada\n1=Salida',
  `user_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `socio_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `compra_text` VARCHAR(100) NULL DEFAULT NULL,
  `venta_text` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `metodo_pago_id` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '\'0\'=>\'Efectivo\',\'1\'=>\'Tarjeta Crédito/Débito\',\'2\'=>\'Deposito\',\'3\'=>\'Cheque\'',
  `ctacorriente_destino_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `caja_id_fk_cm_idx` (`caja_id` ASC),
  INDEX `cargo_id_fk_cm_idx` (`cargo_id` ASC),
  INDEX `compra_id_fk_cm_idx` (`compra_id` ASC),
  INDEX `venta_id_fk_cm_idx` (`venta_id` ASC),
  INDEX `ctacorriente_id_fk_cm_idx` (`ctacorriente_id` ASC),
  CONSTRAINT `caja_id_fk_cm`
    FOREIGN KEY (`caja_id`)
    REFERENCES `frisko`.`cajas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cargo_id_fk_cm`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `frisko`.`cargos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compra_id_fk_cm`
    FOREIGN KEY (`compra_id`)
    REFERENCES `frisko`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ctacorriente_id_fk_cm`
    FOREIGN KEY (`ctacorriente_id`)
    REFERENCES `frisko`.`ctacorrientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venta_id_fk_cm`
    FOREIGN KEY (`venta_id`)
    REFERENCES `frisko`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`compras_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`compras_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`compras_detalle` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `compra_id` BIGINT(20) NOT NULL,
  `articulo_id` BIGINT(20) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `incluir_impuesto` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `tasa_impuesto` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_id_fk_comdet_idx` (`compra_id` ASC),
  INDEX `articulo_id_fk_comdet_idx` (`articulo_id` ASC),
  CONSTRAINT `articulo_id_fk_comdet`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `compra_id_fk_comdet`
    FOREIGN KEY (`compra_id`)
    REFERENCES `frisko`.`compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`departamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`provincias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`provincias` ;

CREATE TABLE IF NOT EXISTS `frisko`.`provincias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `departamento_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `departamento_id_fk_idx` (`departamento_id` ASC),
  CONSTRAINT `departamento_id_fk_prov`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `frisko`.`departamentos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 196
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`distritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`distritos` ;

CREATE TABLE IF NOT EXISTS `frisko`.`distritos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `provincia_id` INT(11) NOT NULL,
  `departamento_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `provincia_id_fk_idx` (`provincia_id` ASC),
  INDEX `departamento_id_fk_dist_idx` (`departamento_id` ASC),
  CONSTRAINT `departamento_id_fk_dist`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `frisko`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `provincia_id_fk_dist`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `frisko`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`docseries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`docseries` ;

CREATE TABLE IF NOT EXISTS `frisko`.`docseries` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `documento_id` INT(11) NOT NULL,
  `deposito_id` INT(11) NOT NULL,
  `serie` INT(3) UNSIGNED ZEROFILL NOT NULL,
  `numero` INT(7) UNSIGNED ZEROFILL NOT NULL,
  `tipo` INT(2) NULL DEFAULT '0' COMMENT '0=Venta\n1=Caja\n2=Almacen\n3=Manufactura',
  PRIMARY KEY (`id`),
  INDEX `deposito_id_fk_docs_idx` (`deposito_id` ASC),
  INDEX `documento_id_fk_docs_idx` (`documento_id` ASC),
  CONSTRAINT `deposito_id_fk_docs`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `documento_id_fk_docs`
    FOREIGN KEY (`documento_id`)
    REFERENCES `frisko`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`guias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`guias` ;

CREATE TABLE IF NOT EXISTS `frisko`.`guias` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `deposito_id` INT(11) NOT NULL,
  `orden_venta_id` BIGINT(20) NULL DEFAULT NULL,
  `socio_id` BIGINT(20) NOT NULL,
  `documento_id` INT(11) NOT NULL DEFAULT '0',
  `direccion` VARCHAR(255) NOT NULL DEFAULT '',
  `fecha` DATE NOT NULL DEFAULT '0000-00-00',
  `serie` INT(3) UNSIGNED ZEROFILL NOT NULL,
  `numero` INT(7) UNSIGNED ZEROFILL NOT NULL,
  `docserie_id` BIGINT(20) NOT NULL,
  `codigo_unico` VARCHAR(100) NULL DEFAULT NULL COMMENT 'serie.numero.docserie_id.deposito_id',
  `estado` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0=Grabado 1=Procesado',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_unico_UNIQUE` (`codigo_unico` ASC),
  INDEX `socio_id_fk_gr_idx` (`socio_id` ASC),
  INDEX `orden_venta_id_fk_gr_idx` (`orden_venta_id` ASC),
  INDEX `documento_id_fk_gr_idx` (`documento_id` ASC),
  INDEX `deposito_id_fk_gr_idx` (`deposito_id` ASC),
  CONSTRAINT `deposito_id_fk_gr`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `documento_id_fk_gr`
    FOREIGN KEY (`documento_id`)
    REFERENCES `frisko`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_gr`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`guias_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`guias_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`guias_detalle` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `guia_id` BIGINT(20) NOT NULL,
  `articulo_id` BIGINT(20) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `deposito_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `estado` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0=Grabado 1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `guia_id_fk_gd_idx` (`guia_id` ASC),
  INDEX `articulo_id_fk_gd_idx` (`articulo_id` ASC),
  CONSTRAINT `articulo_id_fk_gd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `guia_id_fk_gd`
    FOREIGN KEY (`guia_id`)
    REFERENCES `frisko`.`guias` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`i18n`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`i18n` ;

CREATE TABLE IF NOT EXISTS `frisko`.`i18n` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `locale` VARCHAR(6) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `foreign_key` INT(10) NOT NULL,
  `field` VARCHAR(255) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `I18N_LOCALE_FIELD` (`locale` ASC, `model` ASC, `foreign_key` ASC, `field` ASC),
  INDEX `I18N_FIELD` (`model` ASC, `foreign_key` ASC, `field` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`ingresos_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ingresos_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ingresos_detalle` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ingreso_id` BIGINT(20) NOT NULL,
  `articulo_id` BIGINT(20) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `deposito_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `estado` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '0=Grabado 1=Procesado',
  PRIMARY KEY (`id`),
  INDEX `ingreso_id_fk_idet_idx` (`ingreso_id` ASC),
  INDEX `articulo_id_fk_idet_idx` (`articulo_id` ASC),
  CONSTRAINT `articulo_id_fk_idet`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ingreso_id_fk_idet`
    FOREIGN KEY (`ingreso_id`)
    REFERENCES `frisko`.`ingresos` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`menus` ;

CREATE TABLE IF NOT EXISTS `frisko`.`menus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `alias` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `class` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `weight` INT(11) NULL DEFAULT NULL,
  `link_count` INT(11) NULL DEFAULT NULL,
  `params` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frisko`.`links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`links` ;

CREATE TABLE IF NOT EXISTS `frisko`.`links` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NOT NULL DEFAULT '0',
  `menu_id` INT(11) NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `class` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `link` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `target` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `rel` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `lft` INT(11) NULL DEFAULT NULL,
  `rght` INT(11) NULL DEFAULT NULL,
  `visibility_roles` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `params` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `menu_id_fk_idx` (`menu_id` ASC),
  CONSTRAINT `menu_id_fk_us`
    FOREIGN KEY (`menu_id`)
    REFERENCES `frisko`.`menus` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `frisko`.`orden_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_compras` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_compras` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `socio_id` BIGINT(20) NOT NULL DEFAULT '0',
  `compra_id` BIGINT(20) NULL DEFAULT NULL,
  `ingreso_id` BIGINT(20) NULL DEFAULT NULL,
  `fecha` DATE NOT NULL DEFAULT '0000-00-00',
  `estado` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=Guardado\n1=Procesado\n2=Facturado, 3=anulado',
  `total` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `impuesto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `grantotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_oc_idx` (`socio_id` ASC),
  CONSTRAINT `socio_id_fk_oc`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`orden_compras_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_compras_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_compras_detalle` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `orden_compra_id` BIGINT(20) NOT NULL,
  `articulo_id` BIGINT(20) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `precio` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `incluir_impuesto` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `tasa_impuesto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `orden_compra_id_fk_ocd_idx` (`orden_compra_id` ASC),
  INDEX `articulo_id_fk_ocd_idx` (`articulo_id` ASC),
  CONSTRAINT `articulo_id_fk_ocd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orden_compra_id_fk_ocd`
    FOREIGN KEY (`orden_compra_id`)
    REFERENCES `frisko`.`orden_compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`orden_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_ventas` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_ventas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NOT NULL,
  `deposito_id` INT(11) NOT NULL,
  `socio_id` BIGINT(20) NOT NULL,
  `forma_pago_id` BIGINT(20) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0=Proforma\n, 1=Orden Estandar\n, 2=Orden Venta, 3=Anulado',
  `guia_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `venta_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `status_venta` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `status_guia` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `total` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `impuesto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `grantotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `socio_id_fk_ov_idx` (`socio_id` ASC),
  INDEX `deposito_id_fk_ov_idx` (`deposito_id` ASC),
  INDEX `user_id_fk_ov_idx` (`user_id` ASC),
  INDEX `forma_pago_id_fk_ov_idx` (`forma_pago_id` ASC),
  CONSTRAINT `deposito_id_fk_ov`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `forma_pago_id_fk_ov`
    FOREIGN KEY (`forma_pago_id`)
    REFERENCES `frisko`.`forma_pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_ov`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk_ov`
    FOREIGN KEY (`user_id`)
    REFERENCES `frisko`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`orden_ventas_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`orden_ventas_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`orden_ventas_detalle` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `orden_venta_id` BIGINT(20) NOT NULL,
  `articulo_id` BIGINT(20) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `estado` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `deposito_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `incluir_impuesto` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `tasa_impuesto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `orden_venta_id_fk_ovd_idx` (`orden_venta_id` ASC),
  INDEX `articulo_id_fk_ovd_idx` (`articulo_id` ASC),
  CONSTRAINT `articulo_id_fk_ovd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orden_venta_id_fk_ovd`
    FOREIGN KEY (`orden_venta_id`)
    REFERENCES `frisko`.`orden_ventas` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`sessions` ;

CREATE TABLE IF NOT EXISTS `frisko`.`sessions` (
  `id` VARCHAR(40) NOT NULL DEFAULT '',
  `data` TEXT NULL DEFAULT NULL,
  `expires` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`ventas_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`ventas_detalle` ;

CREATE TABLE IF NOT EXISTS `frisko`.`ventas_detalle` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `venta_id` BIGINT(20) NULL DEFAULT NULL,
  `articulo_id` BIGINT(20) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `serie` LONGTEXT NULL DEFAULT NULL COMMENT 'serie de articulos',
  `incluir_impuesto` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `tasa_impuesto` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `venta_id_fk_vd_idx` (`venta_id` ASC),
  INDEX `articulo_id_fk_vd_idx` (`articulo_id` ASC),
  CONSTRAINT `articulo_id_fk_vd`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `frisko`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venta_id_fk_vd`
    FOREIGN KEY (`venta_id`)
    REFERENCES `frisko`.`ventas` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `frisko`.`pos_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frisko`.`pos_settings` ;

CREATE TABLE IF NOT EXISTS `frisko`.`pos_settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `deposito_id` INT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `docserie_id` BIGINT NOT NULL COMMENT 'serie de documento para la guia de remision',
  `documento_venta` VARCHAR(100) NOT NULL,
  `caja_id` BIGINT NULL,
  `socio_id` BIGINT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_fk_ps_idx` (`user_id` ASC),
  INDEX `deposito_id_fk_ps_idx` (`deposito_id` ASC),
  INDEX `docserie_id_fk_ps_idx` (`docserie_id` ASC),
  INDEX `socio_id_fk_ps_idx` (`socio_id` ASC),
  INDEX `caja_id_fk_ps_idx` (`caja_id` ASC),
  CONSTRAINT `user_id_fk_ps`
    FOREIGN KEY (`user_id`)
    REFERENCES `frisko`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deposito_id_fk_ps`
    FOREIGN KEY (`deposito_id`)
    REFERENCES `frisko`.`depositos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `docserie_id_fk_ps`
    FOREIGN KEY (`docserie_id`)
    REFERENCES `frisko`.`docseries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `socio_id_fk_ps`
    FOREIGN KEY (`socio_id`)
    REFERENCES `frisko`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `caja_id_fk_ps`
    FOREIGN KEY (`caja_id`)
    REFERENCES `frisko`.`cajas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `frisko` ;

-- -----------------------------------------------------
-- Placeholder table for view `frisko`.`docseriev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frisko`.`docseriev` (`deposito_id` INT, `id` INT, `documento_id` INT, `nombre` INT, `serie` INT, `numero` INT, `tipo` INT);

-- -----------------------------------------------------
-- View `frisko`.`docseriev`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `frisko`.`docseriev` ;
DROP TABLE IF EXISTS `frisko`.`docseriev`;
USE `frisko`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `frisko`.`docseriev` AS select `ds`.`deposito_id` AS `deposito_id`,`ds`.`id` AS `id`,`ds`.`documento_id` AS `documento_id`,`d`.`nombre` AS `nombre`,`ds`.`serie` AS `serie`,`ds`.`numero` AS `numero`,`ds`.`tipo` AS `tipo` from (`frisko`.`docseries` `ds` join `frisko`.`documentos` `d`) where (`d`.`id` = `ds`.`documento_id`);
USE `frisko`;

DELIMITER $$

USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`insert_existencia_articulos_ap` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`insert_existencia_articulos_ap`
AFTER INSERT ON `frisko`.`articulo_precios`
FOR EACH ROW
begin

INSERT INTO articulos_info(deposito_id, articulo_id, lista_precio_id,articulo_precio_id) values(NEW.deposito_id, NEW.articulo_id, NEW.lista_precio_id,NEW.id);

END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_ingreso_detalle_after_infert` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_ingreso_detalle_after_infert`
AFTER INSERT ON `frisko`.`ingresos`
FOR EACH ROW
begin

IF new.estado=1 THEN
 update ingresos_detalle set deposito_id=new.deposito_id, estado=1 where ingreso_id=new.id;
END IF;
if new.orden_compra_id then
	update orden_compras set status=1, ingreso_id=new.id where id=new.orden_compra_id;
end if;

END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_orden_compra_after_infert` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_orden_compra_after_infert`
AFTER INSERT ON `frisko`.`compras`
FOR EACH ROW
begin
 if new.orden_compra_id then
 	update orden_compras set estado=2, compra_id=new.id where id=new.orden_compra_id;
 end if;
end$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_numero_documento_venta` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_numero_documento_venta`
BEFORE INSERT ON `frisko`.`ventas`
FOR EACH ROW
begin
 update docseries set numero=new.numero+1 where id=new.docserie_id;
end$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_orden_venta_after_infert_status` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_orden_venta_after_infert_status`
AFTER INSERT ON `frisko`.`ventas`
FOR EACH ROW
begin
	if new.orden_venta_id then
		update orden_ventas set venta_id=new.id, status_venta=1 where id = new.orden_venta_id;
	end if;
end$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_saldo_compra_venta` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_saldo_compra_venta`
AFTER INSERT ON `frisko`.`cajas_movimientos`
FOR EACH ROW
begin
DECLARE total decimal(10,2);
DECLARE saldos decimal(10,2);
	if new.compra_id is not null then
		SELECT grantotal INTO total FROM compras WHERE id=NEW.compra_id;
		SELECT saldo INTO saldos FROM compras WHERE id=NEW.compra_id;
        if new.salida < total then
        	update compras set saldo = total - new.salida where id = new.compra_id;
        else
        	update compras set pagado = 1 where id = new.compra_id;
        end if;
        if new.salida = saldos then
        	update compras set saldo = 0, pagado = 1 where id = new.compra_id;
        end if;
    end if;
    
    if new.venta_id is not null then
		SELECT grantotal INTO total FROM ventas WHERE id=NEW.venta_id;
		SELECT saldo INTO saldos FROM ventas WHERE id=NEW.venta_id;
        if new.entrada < total then
        	update ventas set saldo = total - new.entrada where id = new.venta_id;
        else
        	update ventas set cobrado = 1 where id = new.venta_id;
        end if;
        if new.entrada = saldos then
        	update ventas set saldo = 0, cobrado = 1 where id = new.venta_id;
        end if;
    end if;
end$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`distritos_BEFORE_INSERT` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`distritos_BEFORE_INSERT`
BEFORE INSERT ON `frisko`.`distritos`
FOR EACH ROW
BEGIN
 
END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_docserie_numero_guia` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_docserie_numero_guia`
BEFORE INSERT ON `frisko`.`guias`
FOR EACH ROW
begin
	update docseries set numero=new.numero+1 where id=new.docserie_id;
end$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_orden_venta_after_infert` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_orden_venta_after_infert`
AFTER INSERT ON `frisko`.`guias`
FOR EACH ROW
begin
	if new.orden_venta_id then
		update orden_ventas set status_guia=1, guia_id=new.id where id = new.orden_venta_id;
	end if;
END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_existencia_articulos_after_insert_gd` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_existencia_articulos_after_insert_gd`
AFTER INSERT ON `frisko`.`guias_detalle`
FOR EACH ROW
begin

IF new.estado = 1 THEN
	 update articulos_info set existencia=(existencia-new.cantidad), disponible=(disponible-new.cantidad) where deposito_id=new.deposito_id and articulo_id=new.articulo_id;
END IF;

END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_existencia_articulos_after_update_gd` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_existencia_articulos_after_update_gd`
AFTER UPDATE ON `frisko`.`guias_detalle`
FOR EACH ROW
begin

IF new.estado = 1 THEN
	 update articulos_info set existencia=(existencia-new.cantidad), disponible=(disponible-new.cantidad) where deposito_id=new.deposito_id and articulo_id=new.articulo_id;
END IF;

END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_existencia_articulos_after_insert` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_existencia_articulos_after_insert`
AFTER INSERT ON `frisko`.`ingresos_detalle`
FOR EACH ROW
begin

IF new.estado = 1 THEN
	 update articulos_info set existencia=(existencia+new.cantidad), disponible=(disponible+new.cantidad) where deposito_id=new.deposito_id and articulo_id=new.articulo_id;
END IF;

END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_existencia_articulos_after_update` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_existencia_articulos_after_update`
AFTER UPDATE ON `frisko`.`ingresos_detalle`
FOR EACH ROW
begin 
 IF new.estado = 1 THEN 
	 update articulos_info set existencia=(existencia+new.cantidad), disponible=(disponible+new.cantidad) where deposito_id=new.deposito_id and articulo_id=new.articulo_id;
 END IF; 
END$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`update_existencia_articulos_ov` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`update_existencia_articulos_ov`
AFTER UPDATE ON `frisko`.`orden_ventas`
FOR EACH ROW
begin
 if new.status_guia=1 and new.estado=1 then
  update orden_ventas_detalle set estado = 4 where orden_venta_id=new.id;
 end if;
end$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`actualiza_existencia_articulos_after_insert_orden_estandar` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`actualiza_existencia_articulos_after_insert_orden_estandar`
AFTER INSERT ON `frisko`.`orden_ventas_detalle`
FOR EACH ROW
begin
if new.estado=1 then
		update articulos_info set reservada=(reservada+new.cantidad), disponible=(disponible-new.cantidad) where deposito_id=new.deposito_id and articulo_id=new.articulo_id;
    end if;
end$$


USE `frisko`$$
DROP TRIGGER IF EXISTS `frisko`.`actualiza_existencia_articulos_after_update_orden_estandar` $$
USE `frisko`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `frisko`.`actualiza_existencia_articulos_after_update_orden_estandar`
AFTER UPDATE ON `frisko`.`orden_ventas_detalle`
FOR EACH ROW
begin
	if new.estado=1 then
		update articulos_info set reservada=(reservada+new.cantidad), disponible=(disponible-new.cantidad) where deposito_id=new.deposito_id and articulo_id=new.articulo_id;
    end if;
	if new.estado=4 then
		update articulos_info set reservada=(reservada-new.cantidad), disponible=(disponible+new.cantidad) where deposito_id=new.deposito_id and articulo_id=new.articulo_id;
    end if;
end$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
